# Experiments

## How to Handle a Testing Session in The Lab

- Currently in COVID-times, you need prior approval for your visit. You make request on behalf of your participant and will need their full name, e-mail and telephone number. Officially you should try to fill out these things 10 days early, but I’ve done multiple short-notice requests that were approved within an hour. They have been fast in approving lately. The request form can be found here: https://veoci.com/v/p/119522/workflow/5cp6wdmfywdf. Some info for filling out:
  - The approving division head is the linguistics chair, currently Lisa Davidson (e-mail: lisa.davidson@nyu.edu). Fill out this info under ‘VP approver”
  - Under ‘visitor Business/Expertise’ you can just say ‘research participant’
  - Purpose: human subject research
  - PI = Ailís Cournane
  - Building Name: Carter Hall (press search)
  - For the description of why in-person required just mention something about needing in-lab equipment to participate in experiment of the Child Language Lab etc.
  - Also needs to be filled out for the child! (Just put in parent’s e-mail and telephone


+ Alert the security guard before the parents come in. This might involve leaving the name of the parent and age/number of children 
+ Have consent form ready, explain studies and operation, and sign
+ Check Participant Tracker (All Studies) in google drive to see what participant number you are up to and what list you should be running. Note that the participant completed the study on the form afterwards.
+ Note on consent form what number participant they are for each study they do. Adult forms all go in the “completed adult consent forms” folder. Child forms all go in the completed child forms folder for each respective study; if a child participates in more than one study, make a photocopy of the form, write that they participated in more than one study at the top, and place it one each applicable folder.
+ Offer food/snack, be welcoming and accommodating etc
+ Run study(ies)
+ If adults do >=2 studies (if possible), reimburse afterwards with $10 (usually found in top drawer in office room, check w/Ailis) and fill out receipt
+ If the participant is a child, offer a toy and CLL t-shirt
+ As soon as a study is done, add all demographic information to the tracking sheet & CLL-Database sheet for the respective study. Make sure to mark the date, location (lab or name of daycare), P-number, and child’s name.

## How to Handle a Testing Session Over Zoom

### Recruiting / Before the experiment
- After identifying suitable participants for a given study on the “CLL Sign-up Responses”, contact them using the study’s respective template (make sure Calendly link is attached).
- Once the participant has scheduled a time slot on Calendly, send them a confirmation email with the Zoom link you will use, a questionnaire, and a consent form.
- In the message, ask that the guardian be present to help with any technology issues but that they do not interfere with the child’s responses.
- Send a reminder email one day before the participation date. If necessary, remind the participant that they need to complete and send back the consent and questionnaire form before the study can take place.
- Whenever you receive the consent form and questionnaire, upload it to the proper Google Drive/Dropbox folder.
- On the scheduled day, check the respective study’s Participant Tracker to see which trial/list should be used and assign the participant an ID number. 
- Download the appropriate slideshow and run through it to familiarize yourself with the audio prompts and correct any possible animation/timing errors. Additionally, download the scoring sheet (make sure it matches the slideshow and trial/list you are running). 

### Running the study

- Greet child and guardian; take a moment to introduce yourself and try to make participants feel as comfortable as possible.
- Briefly reiterate how the activity will go and gently remind the guardian not to interfere with the child's responses.
- Get the child’s verbal assent (i.e. “Do you want to play this game?”).
- Share your computer screen with the experiment slideshow, ensuring to allow any necessary Zoom access (i.e. “Share computer sound” or “Give screen control”)
- Run the study as trained to do.

### After the Experiment

- Upload the completed scoring sheet to the proper Google Drive/Dropbox folder.
- Add all demographic information to the CLL-Database sheet for the respective study. Make sure to mark the date, location (online), P-number, and child’s name.
- Send a thank-you note to the guardian with a storybook attached.

## How to Handle a Testing Session Onsite (i.e. a daycare)

_TBD_

## Experiment Overviews {#expov}

### Count Kiddo (Maxime) {-} 

Children are introduced to three ‘kippies’ (fun made-up characters) who want to buy some patterned hats from a wizard. The children are told what each hat costs (hats with stars cost a star, hats with hearts cost a heart and hats with circles cost a circle), and that the kippies will each choose a hat. The kippies then choose a hat and the wizard speaks to one of the kippies. The children are instructed to figure out who the wizard is talking to. They will be told that sometimes the wizard talks about the now, but sometimes he talks about how things could be different instead. The wizard could say something along the lines of "I wish that kippie’s hat had hearts, so he would give me a heart!" (corresponding image: three kippies, one with a hat with stars, one with a hat with hearts, and one who used to wear a starry hat but took it off for now). A narrator will repeat the utterance and then ask: “Who’s the king talking to?” After which the child is prompted to tap on the corresponding character displayed on an iPad. In between trials, children will collect stickers/stamps on a separate piece of paper.

- Time: 15-20 minutes
- Age: 3-5
- Materials: Hats and stickers, laptop/tablet to play video, recorder or qualitative answer key

### KidBiComp (Sarah) {-} 

Children meet Sylvia, a young Spanish-English bilingual girl who lives next to a farm. Sylvia invites the child to play a game similar to 'I Spy', where she looks out her window and says phrases like, "the dog runs", "el perro corre", or even "el perro runs." The child will see two different images and has to find the image that matches what Sylvia says. The animals and actions vary, but Sylvia describes them the same way. 

- Time: 15 minutes
- Age: 2-3
- Materials: eye tracker, questionnaire
- Other: Children must be bilingual Spanish-English

### ModForceJr {-} 

Children are introduced to Cat (a cartoon cat) and Logan (a puppet who watches the video with the child). Cat is planning a birthday party, and the kids are told that Logan will make statements about the images of Cat running errands, but that Logan doesn't always pay attention, so sometimes he says something silly. The narrator then says something along the lines of "Cat is going to the bakery to buy a birthday cake for the party! There are two ways to get to the bakery; the red road, and the green road. But uh oh! The green road is blocked" (corresponding image of a blocked green road and open red road). Then Logan will say "to get to the bakery, Cat can't go down the green road." The narrator asks whether the child thinks Logan is right. That model is repeated a few times, sometimes Logan is right and sometimes he is wrong, and then we see an image of the finished party with some fun music!

- Time: 10 minutes
- Age: 3 ½-4 ½ 
- Materials: Answer key, iPad

### Fuzzy NomNoms {-} 

Children are shown two animals on the screen that look very similar (e.g., a sheep and a llama), and are then showed an animal in the middle of the screen that is hiding behind the curtain. It looks like it could be either animal and at this point, the child either hears sentences like "It's maybe a sheep", or "It's probably a sheep", while we track the child’s eye-movements to see what they pay attention to on screen in response to such sentences. In this way, we infer the stages along the development path to learning abstract language. 

- Time: 30 minutes
- Age: 2-3
- Materials: Eye tracker, headband/clips, cutouts of animals for familiarization

### [ON HOLD] All About ME {-} 

Children are introduced to Pterry the Pterodactyl and Cera the Triceratops, who both comment on pictures using words like must, might and is. The child is then asked “who said it better,” and the child comments on whether Pterry or Cera’s comment was better. 

- Time: 15 minutes
- Age: 5-9
- Materials: answer key, iPad, puppets

### CFWaterpark {-}

For this task, children will play a short guessing game involving three animals playing in a waterpark (crocodile, penguin, and giraffe). Children are presented with short stories, followed by some questions about those stories. They are asked to guess where giraffe is, based on where the other two animals are, and are asked to explain their choices. This game allows us to learn more about how children reason about possibilities, and understand what kinds of possibilities they are able to reason over.

- Time: 15 minutes 
- Age: 5-7 & adults
- Materials:

### SqueakyMice {-}

Children are invited to play a computer game over zoom with the researcher. The game involves little stories with different animals (mice, bees, ants, fish) playing in different locations. Some of the animals make noises and some do not, and your child’s task is to pick which groups of animals to click on to see if they’re noisy, based on what the mama animal says. We also ask children to explain their choices, to better understand how they are interpreting the scenario and language. This fun little game helps us learn more about how children understand the kinds of sentences used when we talk about rules and desires/goals.

- Time: 20 minutes
- Age: 5-7 & adults 
- Materials: Scratch, Zoom, computer/laptop, answer key 

### [In Development] Panoo (Maxime)

Children are introduced to a toy character (Panoo) and his friend who looks identical. They are put inside a box and the narrator (Lily) does something to the box, e.g. paints it, accidentally affecting one of the toys as well (e.g. spilling paint). Lily opens the box and looks inside, and says something, e.g. “Oh no Panoo is all wet!”. Then the child is shown the inside of the box where there are Panoo and his friend, one of them wet. The child is asked “Where’s Panoo? Can you find him?” while we track the child’s eye-movements to see what they pay attention to on screen in response to such sentences. In this way, we try to infer whether they updated their discourse representation with different types of information (factual, modal and counterfactual).  

- Time: 20 minutes
- Age: 2&3
- Materials: Eye tracker, headband/clips, toy Lily.


### [Completed] Exhaustivity (Alicia) {-} 

Children meet Og, the caveman. Og looks at pictures of animals and objects, and then he describes the pictures, but sometimes he says something that's wrong or a little silly. For example, if Og sees a picture of two blue ducks and one red one, he might say "There are two blue ducks" (a correct thing), or he might say "There are two red ducks" (a silly thing). The child's job is to reward Og with strawberries to help him learn what a good way to describe the picture versus what a silly way is. When Og does a good job describing the picture, he should get three strawberries. When Og says something silly, he should get one strawberry or maybe two. 

- Time: 10-12 minutes 
- Age: 4-6
- Materials: Answer sheet, laptop to play video, toy strawberries






