# Logistics

## Lab Meetings ^[Before the semester begins, the lab manager will contact the lab managers/PI of either lab spaces to check availability and block of a time slot that works best for lab members.]

We hold lab meetings once a week during the semester and at the discretion of the PI during the summer. Lab meetings usually involve data blitzes, presentations (lab internal and external) and feedback on projects. 

## Location

We use either the __Sociolinguistics Lab__ (Floor 3) or __Phonetics and Experimental Phonology__ (PEP; Floor 5). 

## Contacts

- Socio Lab Manager: Sarah Phillips (sarah.philips@nyu.edu)
- PEP Lab PI: Dr. Lisa Davison (lisa.davidson@nyu.edu)

## Snacks

The lab manager is entrusted to get snacks for each lab meeting. The lab usually allots a budget of $20/wk for bagels and coffee. After buying said snacks, the lab manager is reimbursed from the PI’s research funds. 

## Recurring Events

- At the end of each week, RAs and Interns must make sure consent forms are refilled, receipts are catalogued and data is digitized 
- They must also print new flyers and put them up around NYU and the environs. 
