# Recruiting and Engagement (MOST IMPORTANT THING)

## Recruiting

Recruiting involves a combination of calling/emailing daycares, parents, and scheduling participants that sign up through the lab’s Google form, or contacting individuals who have participated in our research before. We also use social media platforms (IG, FB) to recruit, but posting content and boosting some posts (i.e., paying to have them appear on people’s feeds, to increase sign-ups). We also use word-of-mouth and tap our own networks. Getting child participants is very difficult, so we must work extra hard on this and be creative!

### Calling Off-Campus Sites {-}

Calls should ideally be made from the phone in the lab (Phone # 212 998 7916). To call, dial 9 then 1 followed by the phone number. We primarily call daycares in the 5 boroughs as well as NJ, Long Island and Westchester County. 

- Prior to making a phone call, study the calling script (found on the Dropbox under 'All Recruiting & Testing Docs) and get a feel for the kind of responses we give. 
- Don’t memorize the script verbatim at the risk of sounding too robotic. You want to sound friendly and stress that the responsibilities of the daycare will be minimal. 
- Try not to use the word “experiment”, as this can sound invasive and can turn people off. Use phrases like “we are running a study” or “we play fun games with kids, and their answers provide us with important information about how they process language”
- It is helpful to shadow a current RA/PhD Student to get a sense of the mechanics of the phone call. 
- Once you feel comfortable making a call,  call daycares listed under the Locations Tab on the CLL-Database (or add new ones). _Make sure you understand how the database works, and you take good notes on locations!
- As you work your way through a list, update contact information if needed and make comments on responses from the contact at the daycare. Comments include:
    - If interested, send an email with the required attachments (DropBox/ALL RECRUITING & TESTING DOCS: look for most up to date stamped IRB forms for the following: Institutional Consent, Letter of Cooperation and Consent Forms) which can be found as a template in the lab email. Once you send an email, flag that you have emailed them and make a note to follow up in a week
    -  If completely uninterested and do not wish to be called back, flag the day care and make sure not to call again. 
- If a daycare responds with the required documents filled out, send the Letter Cooperation to the PI for approval from the IRB.
- Once approved, give a week or two to have the daycare get parents to sign consent forms and then schedule a day to go in. 

### Facebook & Instagram Outreach {-}

We should be posting on Facebook and Instagram regularly (somewhere between 1 and 3 times a week). Try not to post multiple times a day, but rather, spread it out over the week. You can do this by [scheduling](https://blog.hootsuite.com/how-to-schedule-facebook-posts/) posts.

Content generally consists of cool/informative videos about kids and language learning, Lab Member spotlights, and announcements about new studies and activities. Look at our previous posts for inspiration, or feel free to start a new series/trend. In general, don’t make it too wordy and include visuals if possible! If we have something especially important to post (e.g. our lab video when it is complete), you can talk to Ailis about paying to “boost” the post, so it reaches more users. Run any language facts by Ailis and/or PhD Students before posting, to make sure they are scientifically accurate and up-to-date and consistent with the lab brand. 

Aside from posting on our own page, posting in existing groups makes a BIG difference. Local neighborhood groups, NY parent groups, kids activities groups, and groups for local institutions (local parks, childrens’ museums, etc.) are all good places to post. Sometimes this involves applying to the group or contacting the admins of the group directly, which can all be done using the lab facebook page.

### Scheduling {-} 

- At the beginning of each semester, RAs should pick out times they can be in the lab and block out those times on the google calendar. 
- Once we have the times filled out, the lab manager/RA can fill up those times in the [Calendly](https://calendly.com/), the lab’s scheduling system.
- When adults or parents of sign up through the google form through the website, their information ends up in a database of sign ups (which can be found in the Google Drive).
- An RA then follows up with participants in these lists by sending an email from the lab account with the study information and a [Calendly link](https://calendly.com/nyuchildlanguagelab) to schedule a time to come in. 
- Once they sign up, both parties will receive a notification and the time slot will be automatically added to the lab calendar. 
- The RA will then write a confirmation e-mail to the parent, and (if study is online) send a consent form for the caregiver to fill out - each RA is responsible for sending these (template emails for each study can be found in the lab gmail account). 
- A day before testing, the participant will receive a reminder. 
- The RA scheduled to work that time slot will be responsible for running the experiment. 
