# Publications ^[Adapted from Noor Lab (Noor, 2012)]

- Authorship on scientific publications is based on significant contributions to the intellectual input, execution of studies, and writing of papers. Here is the statement on authorship from the journal Evolution: “Authorship of a paper carries with it responsibility as well as credit. All those whose names appear as authors should have played a significant role in designing or carrying out the research, writing the manuscript, or providing extensive guidance to the execution of the project. They should be able to present and defend the work in a public forum.”

- Within the CLL, the PI (Ailís Cournane) has final say on all authorship issues for work conducted by lab members in whole or in part during one’s tenure in the lab. However, as a general guideline, the “default” policies are stated below. These are subject to change without notice and to modification for specific circumstances, including but not limited to exceptionally high or minimal contribution in one or more areas.

- For all authorship issues, provisional authorship may be indicated prior to submission, but authorship and author order will not be finalized until the time of manuscript submission, and that decision falls upon the laboratory PI. __Provisional authorship or author position is no guarantee of authorship or author position on the final submission.__

- Regarding standard research publications, the criterion for co-authorship is contribution of (100/X)% in any one or combination of the following three areas: intellectual input (including initial design and subsequent modification and development of the project); execution (including data analysis); and writing of the paper (including figure and table preparation) for submission. X denotes the number of potential authors contributing to the study. For example, if one of three potential authors contributes 15% to all three areas, they may appear as an author of the paper, since their total contribution is 45% (15% ´ 3), which is greater than the 33% (100/3) minimum. We also abide by the Evolution criterion that all authors should be able to present and defend all the work, not just their piece of the work, in a public forum. Such a presentation should include accurate and thorough discussion of the relation of the work to other published studies on the topic. There must have been at least some detectable intellectual input and engagement; __one cannot have been merely a “lab-hand.”__

- To be considered for “first author”, the researcher must have contributed >50% of the writing of the final draft as well as (100/X)% to either the intellectual input or execution of the project. If the paper drafts given to the PI are so poorly prepared (as determined by the PI) that rewriting from scratch is easier than editing, first authorship by the writer is forfeited. The first author has __no more than 4 months__ from the end of data collection for a particular publication, as determined by the lab PI, to prepare the paper draft. Failure to produce a well-prepared draft in this timeframe may forfeit the right to first-authorship.

- For review papers, authorship requires the incorporation of a significant amount of writing, amounting to greater than two paragraphs of text. As above, if a potential author submits text that is either rewritten or otherwise omitted from the final version, authorship may be nullified.

